// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR3ovLqX3FgAP1jLf6shNUOR-Cp-ANXrY',
    appId: '1:756006585440:web:e3a4cd83b4f9c232196f05',
    messagingSenderId: '756006585440',
    projectId: 'smu-clothes-b872b',
    authDomain: 'smu-clothes-b872b.firebaseapp.com',
    storageBucket: 'smu-clothes-b872b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAeUGi-VWtQA9Mp_BTdgcZCcj8YOGAR-k',
    appId: '1:756006585440:android:d042afa674700f98196f05',
    messagingSenderId: '756006585440',
    projectId: 'smu-clothes-b872b',
    storageBucket: 'smu-clothes-b872b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD86XWfLXX4VELgOFFTmjEq_AS6hZubvM',
    appId: '1:756006585440:ios:350e95d570c0f8e8196f05',
    messagingSenderId: '756006585440',
    projectId: 'smu-clothes-b872b',
    storageBucket: 'smu-clothes-b872b.appspot.com',
    iosClientId: '756006585440-86g1u56kkmjtsjgg16behqnhj69o8j3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.atham',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD86XWfLXX4VELgOFFTmjEq_AS6hZubvM',
    appId: '1:756006585440:ios:350e95d570c0f8e8196f05',
    messagingSenderId: '756006585440',
    projectId: 'smu-clothes-b872b',
    storageBucket: 'smu-clothes-b872b.appspot.com',
    iosClientId: '756006585440-86g1u56kkmjtsjgg16behqnhj69o8j3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.atham',
  );
}
